from mongoengine import *

class Zatiq_Meat_Types(EmbeddedDocument):
   bear = BooleanField(default=False)
   beef = BooleanField(default=False)
   buffalo = BooleanField(default=False)
   calf = BooleanField(default=False)
   caribou = BooleanField(default=False)
   goat = BooleanField(default=False)
   ham = BooleanField(default=False)
   horse = BooleanField(default=False)
   kangaroo = BooleanField(default=False)
   lamb = BooleanField(default=False)
   moose = BooleanField(default=False)
   mutton = BooleanField(default=False)
   opossum = BooleanField(default=False)
   pork = BooleanField(default=False)
   bacon = BooleanField(default=False)
   rabbit = BooleanField(default=False)
   snake = BooleanField(default=False)
   squirrel = BooleanField(default=False)
   turtle = BooleanField(default=False)
   veal = BooleanField(default=False)
   chicken = BooleanField(default=False)
   hen = BooleanField(default=False)
   duck = BooleanField(default=False)
   goose = BooleanField(default=False)
   ostrich = BooleanField(default=False)
   quail = BooleanField(default=False)
   turkey = BooleanField(default=False)
